INSERT INTO d_shipping_ticket_print_queue(
            create_date, update_date, printer_id, print_type, 
            customer_name, part_name, part_no, lot_no, mfg_date, plan_code, 
            time_of_delivery, checker, packing_date, model, color, serial_no, 
            quantity, location, quality_rank)
    VALUES (CURRENT_TIMESTAMP,
            CURRENT_TIMESTAMP,
            /*printerId*/,
            /*printType*/,
            /*customerName*/,
            /*partName*/,
            /*partNo*/,
            /*lotNo*/,
            /*mfgDate*/,
            /*planCode*/,
            /*timeOfDelivery*/,
            /*checker*/,
            /*packingDate*/,
            /*model*/,
            /*color*/,
            /*serialNo*/,
            /*quantity*/,
            /*location*/,
            /*qualityRank*/)